##################
#   Server
##################
server:
  context-path: /spfj8
  
########################
#   Database Settings
########################
spring:
  datasource:
    url: jdbc:h2:mem:es-chanllenge;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    #url: jdbc:h2:mem:es-chanllenge;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;INIT=CREATE SCHEMA IF NOT EXISTS es-chanllenge;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
    #schema: es-chanllenge
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

##################
#   H2 Settings
##################
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false